log_level: WARN
plugins:
    ArtifactoryDetector: true
    AWSKeyDetector: true
    AzureStorageKeyDetector: true
    BasicAuthDetector: true
    CloudantDetector: true
    DiscordBotTokenDetector: true
    GitHubTokenDetector: true
    GitLabTokenDetector: true
    Base64HighEntropyString: 4.5
    HexHighEntropyString: 3
    IbmCloudIamDetector: true
    IbmCosHmacDetector: true
    IPPublicDetector: true
    JwtTokenDetector: true
    KeywordDetector: true
    MailchimpDetector: true
    NpmDetector: true
    OpenAIDetector: true
    PrivateKeyDetector: true
    PypiTokenDetector: true
    SendGridDetector: true
    SlackDetector: true
    SoftlayerDetector: true
    SquareOAuthDetector: true
    StripeDetector: true
    TelegramBotTokenDetector: true
    TwilioKeyDetector: true
