language: python
python:
    - "3.8"
before_install:
- pip install --upgrade setuptools packaging
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

before_script:
    - pip install --upgrade pip
script:
    #If this is the first commit on a branch, use 0000000000000000000000000000000000000000 to match the behavior of GitLab CI.
    - export PATH="$HOME/.local/bin:$PATH"
    - echo $COMMIT_RANGE
    - echo $TRAVIS_COMMIT_RANGE
    - export COMMIT_RANGE=${TRAVIS_COMMIT_RANGE:-"0000000000000000000000000000000000000000"}
    - echo $COMMIT_RANGE
    - echo $TRAVIS_COMMIT_RANGE
    - export LAST_COMMIT=${COMMIT_RANGE%%.*}
    - echo $LAST_COMMIT
    - pip -V
    - pip list
    - pip --version
    - pwd
    - which cjk6_source_ci_secrets
    - pip show cjk6_source_ci_secrets
    - which detect-secrets
    - pip show detect-secrets
    - cjk6_source_ci_secrets --since $LAST_COMMIT --includesMergeCommit --log INFO
