language: python
python:
    - "3.8"
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
script:
    #If this is the first commit on a branch, use 0000000000000000000000000000000000000000 to match the behavior of GitLab CI.
    - export COMMIT_RANGE=${TRAVIS_COMMIT_RANGE:-"10"}
    - export LAST_COMMIT=${COMMIT_RANGE%%.*}
    - echo $LAST_COMMIT
    - pwd
    - ls
    - python ci_secrets/main.py --since $LAST_COMMIT --includesMergeCommit --log INFO --path /home/travis/build/cjk6-source/ci_secrets
